---
- name: Gather all host metadata
  hosts: all
  # strategy: debug
  tasks: []

- name: apply common configuration to all nodes
  hosts: master,slave
  roles:
    - common

- name: configure master
  hosts: master
  # strategy: debug
  roles:
    - master

- name: configure slave
  hosts: slave
  # strategy: debug
  roles:
    - slave

- name: configure master
  hosts: master
  become: yes
  become_user: postgres
  tasks:
    - postgresql_user: name=rails password=secret role_attr_flags=SUPERUSER

- name: configure pgpool
  hosts: pgpool
  roles:
    - pgpool